/**
 * SCP-Unknown- game data (CC BY-SA 3.0 derivative content).
 * SCP articles © respective authors on SCP Wiki.
 */
const GAME_DATA = {
  version: "0.3.7",
  staminaMaxBase: 30,
  staminaRegenMs: 120000, // 2 min per token
  chamberUnlockCount: 7,
  chamberMaxSlots: 6,

  classColors: {
    Safe: "#7a8a58",
    Euclid: "#5a7a98",
    Keter: "#b03028",
    Thaumiel: "#c4a34a",
  },

  siteUpgrades: [
    { level: 1, name: "仮設収容区画", cost: 0, materials: {}, staminaBonus: 0, chamberSlots: 2, dropBonus: 0,
      desc: "プレハブと仮設フェンス。許可証の備蓄は最小限で、試験槽は2基だけ稼働する。" },
    { level: 2, name: "標準実験棟", cost: 500, materials: { p_scrap: 20, p_wire: 12, p_resin: 8 },
      staminaBonus: 10, chamberSlots: 3, dropBonus: 0.05,
      desc: "隔離壁と観察窓を備えた常設棟。基礎部品を壁材にし、許可証上限と試験槽が伸びる。" },
    { level: 3, name: "深層隔離区画", cost: 2000, materials: { p_alloy: 8, p_circuit: 6, obj_gear: 2 },
      staminaBonus: 20, chamberSlots: 4, dropBonus: 0.1,
      desc: "地下階層の本格隔離。合金と時計部品でKeter級の一時収容を支える。" },
    { level: 4, name: "Thaumiel運用棟", cost: 8000, materials: { p_cell: 6, p_anomalon: 3, obj_key: 2, obj_blood: 2 },
      staminaBonus: 30, chamberSlots: 5, dropBonus: 0.15,
      desc: "異常を戦力化する専用棟。電源と収容品で運用許可を通す。" },
    { level: 5, name: "Site-Unknown 中枢", cost: 25000, materials: { p_anomalon: 12, p_cell: 8, obj_voidorb: 1, obj_seed: 1 },
      staminaBonus: 50, chamberSlots: 6, dropBonus: 0.25,
      desc: "サイト中枢。重力殻と再構築種子を核に据え、回収効率が最大になる。" },
  ],

  /**
   * 拠点プロトコルツリー。施設レベルで得た点を隣接ノードへ割り振る（PoE パッシブの縮小版）。
   * start は無料。小ノード/著名/キーストーンはすべて 1 点。
   */
  siteTree: {
    startId: "n_start",
    startPoints: 3,
    pointsPerLevel: 4,
    respecCost: 400,
    nodes: [
      { id: "n_start", name: "仮設起点", kind: "start", cluster: "core", icon: "start", x: 500, y: 340, cost: 0,
        effects: {}, desc: "サイト運用の起点。隣接ノードへプロトコル点を割り振る。" },

      { id: "n_s1", name: "予備弾倉", kind: "small", cluster: "sentry", icon: "ammo", x: 500, y: 270, cost: 1,
        effects: { sentryAmmo: 4 }, desc: "セントリー残弾 +4。" },
      { id: "n_s2", name: "弾倉拡張", kind: "small", cluster: "sentry", icon: "ammo", x: 500, y: 210, cost: 1,
        effects: { sentryAmmo: 4 }, desc: "セントリー残弾 +4。" },
      { id: "n_s3", name: "射界校正", kind: "small", cluster: "sentry", icon: "radius", x: 430, y: 210, cost: 1,
        effects: { sentryRadius: 8 }, desc: "セントリー射程 +8。" },
      { id: "n_s4", name: "測距儀", kind: "small", cluster: "sentry", icon: "rangefinder", x: 570, y: 210, cost: 1,
        effects: { sentryRadius: 8 }, desc: "セントリー射程 +8。" },
      { id: "n_s5", name: "自動射撃管制", kind: "notable", cluster: "sentry", icon: "fire-control", x: 500, y: 145, cost: 1,
        effects: { sentryAmmo: 8, sentryRadius: 10 }, desc: "残弾 +8、射程 +10。" },
      { id: "n_s6", name: "徹甲弾芯", kind: "small", cluster: "sentry", icon: "ap-core", x: 430, y: 145, cost: 1,
        effects: { sentrySave: 0.15 }, desc: "セントリー射撃の 15% は残弾を消費しない。" },
      { id: "n_sk", name: "砲台網", kind: "keystone", cluster: "sentry", icon: "turret-net", x: 500, y: 75, cost: 1,
        effects: { sentryMax: 1, sentryAmmo: 10, sentryRadius: 12 }, desc: "設置上限 +1、残弾 +10、射程 +12。" },

      { id: "n_g1", name: "予算監査", kind: "small", cluster: "gear", icon: "budget", x: 575, y: 340, cost: 1,
        effects: { enhanceBudget: 0.95 }, desc: "装備強化の予算 -5%。" },
      { id: "n_g2", name: "発注最適化", kind: "small", cluster: "gear", icon: "budget", x: 655, y: 340, cost: 1,
        effects: { enhanceBudget: 0.95 }, desc: "装備強化の予算 -5%。" },
      { id: "n_g3", name: "補給優先", kind: "notable", cluster: "gear", icon: "supply", x: 735, y: 300, cost: 1,
        effects: { enhanceMat: 0.9 }, desc: "装備強化の素材 -10%。" },
      { id: "n_g4", name: "レシピ整理", kind: "small", cluster: "gear", icon: "recipe", x: 735, y: 380, cost: 1,
        effects: { craftCost: 0.9 }, desc: "クラフト予算 -10%。" },
      { id: "n_gk", name: "工廠規格", kind: "keystone", cluster: "gear", icon: "factory", x: 820, y: 340, cost: 1,
        effects: { enhanceMat: 0.85, enhanceBudget: 0.9, craftCost: 0.9 },
        desc: "強化素材 -15%、強化予算 -10%、クラフト予算 -10%。" },

      { id: "n_d1", name: "選別眼", kind: "small", cluster: "salvage", icon: "sort-eye", x: 500, y: 410, cost: 1,
        effects: { dismantleChance: 0.08 }, desc: "分解時 8% で追加部品。" },
      { id: "n_d2", name: "残骸鑑定", kind: "small", cluster: "salvage", icon: "sort-eye", x: 500, y: 475, cost: 1,
        effects: { dismantleChance: 0.08 }, desc: "分解時 8% で追加部品。" },
      { id: "n_d3", name: "歩留まり", kind: "small", cluster: "salvage", icon: "yield", x: 430, y: 475, cost: 1,
        effects: { dismantleChance: 0.1 }, desc: "分解時 10% で追加部品。" },
      { id: "n_d4", name: "再結晶", kind: "small", cluster: "salvage", icon: "crystal", x: 570, y: 475, cost: 1,
        effects: { dismantleChance: 0.08 }, desc: "分解時 8% で追加部品。" },
      { id: "n_d5", name: "選別回収", kind: "notable", cluster: "salvage", icon: "salvage", x: 500, y: 545, cost: 1,
        effects: { dismantleChance: 0.12 }, desc: "分解時 12% で追加部品。" },
      { id: "n_dk", name: "解体選別", kind: "keystone", cluster: "salvage", icon: "scrap-select", x: 500, y: 615, cost: 1,
        effects: { dismantleChance: 0.2, dismantleExtra: 2 }, desc: "分解時 20% で追加部品 +2。" },

      { id: "n_o1", name: "許可枠", kind: "small", cluster: "ops", icon: "permit", x: 425, y: 340, cost: 1,
        effects: { stamina: 5 }, desc: "許可証上限 +5。" },
      { id: "n_o2", name: "備蓄拡大", kind: "small", cluster: "ops", icon: "permit", x: 345, y: 340, cost: 1,
        effects: { stamina: 5 }, desc: "許可証上限 +5。" },
      { id: "n_o3", name: "回収網", kind: "small", cluster: "ops", icon: "loot", x: 345, y: 280, cost: 1,
        effects: { dropBonus: 0.03 }, desc: "ドロップ補正 +3%。" },
      { id: "n_o4", name: "現場回収", kind: "small", cluster: "ops", icon: "loot", x: 345, y: 400, cost: 1,
        effects: { dropBonus: 0.03 }, desc: "ドロップ補正 +3%。" },
      { id: "n_o5", name: "収容効率", kind: "notable", cluster: "ops", icon: "contain", x: 260, y: 340, cost: 1,
        effects: { stamina: 10, dropBonus: 0.04 }, desc: "許可証上限 +10、ドロップ +4%。" },
      { id: "n_ok", name: "サイト運用", kind: "keystone", cluster: "ops", icon: "site-ops", x: 175, y: 340, cost: 1,
        effects: { chamber: 1, reconSpeed: 1.15 }, desc: "試験槽 +1、巡回速度 +15%。" },

      { id: "n_tn", name: "連係・北東", kind: "small", cluster: "link", icon: "ammo", x: 560, y: 275, cost: 1,
        effects: { sentryAmmo: 2 }, desc: "砲台と工廠をつなぐ。残弾 +2。" },
      { id: "n_te", name: "連係・南東", kind: "small", cluster: "link", icon: "budget", x: 560, y: 405, cost: 1,
        effects: { enhanceBudget: 0.97 }, desc: "工廠と解体をつなぐ。強化予算 -3%。" },
      { id: "n_ts", name: "連係・南西", kind: "small", cluster: "link", icon: "sort-eye", x: 440, y: 405, cost: 1,
        effects: { dismantleChance: 0.05 }, desc: "解体と運用をつなぐ。分解追加 5%。" },
      { id: "n_tw", name: "連係・北西", kind: "small", cluster: "link", icon: "radius", x: 440, y: 275, cost: 1,
        effects: { sentryRadius: 6 }, desc: "運用と砲台をつなぐ。射程 +6。" },
    ],
    edges: [
      ["n_start", "n_s1"], ["n_s1", "n_s2"], ["n_s2", "n_s3"], ["n_s2", "n_s4"],
      ["n_s2", "n_s5"], ["n_s5", "n_s6"], ["n_s5", "n_sk"], ["n_s6", "n_sk"],
      ["n_start", "n_g1"], ["n_g1", "n_g2"], ["n_g2", "n_g3"], ["n_g2", "n_g4"],
      ["n_g3", "n_gk"], ["n_g4", "n_gk"],
      ["n_start", "n_d1"], ["n_d1", "n_d2"], ["n_d2", "n_d3"], ["n_d2", "n_d4"],
      ["n_d2", "n_d5"], ["n_d5", "n_dk"],
      ["n_start", "n_o1"], ["n_o1", "n_o2"], ["n_o2", "n_o3"], ["n_o2", "n_o4"],
      ["n_o2", "n_o5"], ["n_o5", "n_ok"],
      ["n_start", "n_tn"], ["n_tn", "n_s1"], ["n_tn", "n_g1"],
      ["n_start", "n_te"], ["n_te", "n_g1"], ["n_te", "n_d1"],
      ["n_start", "n_ts"], ["n_ts", "n_d1"], ["n_ts", "n_o1"],
      ["n_start", "n_tw"], ["n_tw", "n_o1"], ["n_tw", "n_s1"],
    ],
  },

  skills: {
    // --- Active ---
    snap_neck: { id: "snap_neck", name: "首折り", type: "active", power: 1.4, target: "single", element: "physical", desc: "単体に強力な物理打撃。" },
    rage_cry: { id: "rage_cry", name: "激怒の叫び", type: "active", power: 0, target: "self", buff: { atk: 1.5, turns: 3 }, desc: "自身の物攻を上げる。" },
    plague_touch: { id: "plague_touch", name: "ペストの接触", type: "active", power: 0.8, target: "all", element: "anomaly", desc: "全体に異能ダメージ＋毒。" },
    regen_bulk: { id: "regen_bulk", name: "適応再生", type: "active", power: 0, target: "self", heal: 0.25, desc: "自身のHPを回復。" },
    shadow_lunge: { id: "shadow_lunge", name: "影の突進", type: "active", power: 1.2, target: "single", element: "physical", desc: "高速の単体攻撃。" },
    mirror_blast: { id: "mirror_blast", name: "鏡面爆発", type: "active", power: 1.0, target: "all", element: "anomaly", desc: "全体異能攻撃。" },
    docile_aura: { id: "docile_aura", name: "従順の波動", type: "active", power: 0, target: "party", buff: { def: 1.3, turns: 2 }, desc: "味方全体の防御を上げる。" },
    candy_offer: { id: "candy_offer", name: "キャンディ提供", type: "active", power: 0, target: "party", heal: 0.15, desc: "味方全体を回復。" },
    machine_gun: { id: "machine_gun", name: "機関銃掃射", type: "active", power: 0.6, target: "all", element: "physical", hits: 3, desc: "全体に3回物理攻撃。" },
    void_pull: { id: "void_pull", name: "虚無吸引", type: "active", power: 1.1, target: "single", element: "anomaly", desc: "単体に吸引ダメージ。" },
    bone_crush: { id: "bone_crush", name: "骨砕き", type: "active", power: 1.3, target: "single", element: "physical", desc: "単体物理の大ダメージ。" },
    time_stop: { id: "time_stop", name: "時間停止", type: "active", power: 0, target: "party", buff: { spd: 2.0, turns: 1 }, desc: "味方の速度を一時的に倍増。" },
    fire_breath: { id: "fire_breath", name: "炎息", type: "active", power: 1.0, target: "all", element: "anomaly", desc: "全体に炎属性異能。" },
    ink_spray: { id: "ink_spray", name: "墨噴射", type: "active", power: 0.7, target: "all", element: "anomaly", debuff: { acc: 0.7, turns: 2 }, desc: "全体に墨で視界妨害。" },
    luck_drain: { id: "luck_drain", name: "幸運吸収", type: "active", power: 0.5, target: "single", element: "anomaly", desc: "敵の運を吸い取る。" },
    info_siphon: { id: "info_siphon", name: "情報吸い上げ", type: "active", power: 0, target: "single", steal: true, desc: "敵のドロップ品を吸い上げる。" },
    mass_siphon: { id: "mass_siphon", name: "全情報吸い上げ", type: "active", power: 0, target: "all", steal: true, desc: "敵全体から情報を吸い上げる。" },
    reclassify: { id: "reclassify", name: "再分類", type: "active", power: 0, target: "self", buff: { all: 1.2, turns: 3 }, desc: "自身の全能力を一時強化。" },
    shield_wall: { id: "shield_wall", name: "隔離壁", type: "active", power: 0, target: "party", buff: { def: 1.5, turns: 2 }, desc: "味方に隔離壁を展開。" },
    cognito_hazard: { id: "cognito_hazard", name: "認知危害", type: "active", power: 0.9, target: "all", element: "anomaly", desc: "認知フィルタを破壊し全体にダメージ。" },
    blood_rite: { id: "blood_rite", name: "血の儀式", type: "active", power: 1.5, target: "single", element: "anomaly", selfCost: 0.1, desc: "自身のHPを消費して強力攻撃。" },
    teleport_strike: { id: "teleport_strike", name: "転移打撃", type: "active", power: 1.1, target: "single", element: "physical", desc: "瞬間移動からの打撃。" },
    sound_wave: { id: "sound_wave", name: "音波", type: "active", power: 0.85, target: "all", element: "anomaly", desc: "音波で全体攻撃。" },
    rust_touch: { id: "rust_touch", name: "錆の接触", type: "active", power: 0.8, target: "single", element: "anomaly", debuff: { def: 0.7, turns: 3 }, desc: "防御を蝕む。" },
    pack_howl: { id: "pack_howl", name: "群れの遠吠え", type: "active", power: 0, target: "party", buff: { atk: 1.25, turns: 2 }, desc: "味方の攻撃力を上げる。" },
    phase_shift: { id: "phase_shift", name: "位相移動", type: "active", power: 0, target: "self", buff: { eva: 0.5, turns: 2 }, desc: "回避率を大幅に上げる。" },
    gravity_crush: { id: "gravity_crush", name: "重力圧壊", type: "active", power: 1.2, target: "all", element: "anomaly", desc: "重力で全体を圧壊。" },
    heal_pulse: { id: "heal_pulse", name: "治癒パルス", type: "active", power: 0, target: "party", heal: 0.2, desc: "味方全体を回復。" },
    fear_gaze: { id: "fear_gaze", name: "恐怖の視線", type: "active", power: 0, target: "all", debuff: { atk: 0.7, turns: 2 }, desc: "敵全体の攻撃力を下げる。" },
    data_mine: { id: "data_mine", name: "データ採掘", type: "active", power: 0.6, target: "single", element: "anomaly", steal: true, desc: "データを採掘してアイテム化。" },
    containment_field: { id: "containment_field", name: "収容フィールド", type: "active", power: 0, target: "all", debuff: { spd: 0.5, turns: 2 }, desc: "敵の速度を半減。" },
    anomaly_burst: { id: "anomaly_burst", name: "異常爆発", type: "active", power: 1.0, target: "all", element: "anomaly", desc: "純粋な異能爆発。" },
    slash: { id: "slash", name: "斬撃", type: "active", power: 1.0, target: "single", element: "physical", desc: "基本的な斬撃。" },
    bash: { id: "bash", name: "打撃", type: "active", power: 0.9, target: "single", element: "physical", desc: "基本的な打撃。" },
    // --- Passive ---
    hardened: { id: "hardened", name: "硬化皮膚", type: "passive", stat: { def: 1.15 }, desc: "防御+15%。" },
    swift: { id: "swift", name: "高速神経", type: "passive", stat: { spd: 1.2 }, desc: "速度+20%。" },
    lucky: { id: "lucky", name: "幸運", type: "passive", stat: { luck: 1.3 }, desc: "運+30%。" },
    super_lucky: { id: "super_lucky", name: "超幸運", type: "passive", stat: { luck: 1.6 }, desc: "運+60%。" },
    crit_master: { id: "crit_master", name: "急所看破", type: "passive", stat: { crit: 0.2, critDmg: 0.3 }, desc: "クリ率+20%、クリダメ+30%。" },
    regen_passive: { id: "regen_passive", name: "自然再生", type: "passive", stat: { regen: 0.03 }, desc: "毎ターンHP3%回復。" },
    thorns: { id: "thorns", name: "反射棘", type: "passive", stat: { thorns: 0.15 }, desc: "被弾時15%反射。" },
    anomaly_amp: { id: "anomaly_amp", name: "異能増幅", type: "passive", stat: { anm: 1.2 }, desc: "異能+20%。" },
    iron_will: { id: "iron_will", name: "鉄の意志", type: "passive", stat: { def: 1.1, hp: 1.1 }, desc: "HP・防御+10%。" },
    predator: { id: "predator", name: "捕食者", type: "passive", stat: { atk: 1.15 }, desc: "物攻+15%。" },
    siphon_mastery: { id: "siphon_mastery", name: "吸い上げ熟練", type: "passive", stat: { stealMult: 3.0 }, desc: "吸い上げ成功率3倍。" },
    open_siphon: { id: "open_siphon", name: "開幕吸い上げ", type: "passive", onBattleStart: "mass_siphon", desc: "戦闘開始時に全情報吸い上げを発動。" },
    artifact_hunter: { id: "artifact_hunter", name: "アーティファクト探索", type: "passive", stat: { artifactChance: 0.05 }, desc: "吸い上げ品がアーティファクト化する確率+5%。" },
    docile_nature: { id: "docile_nature", name: "従順性", type: "passive", stat: { luck: 1.1, hp: 1.05 }, desc: "運・HP微増。" },
    plague_carrier: { id: "plague_carrier", name: "疫病媒介", type: "passive", stat: { anm: 1.1 }, onHit: "poison", desc: "攻撃時に毒を付与。" },
    adaptive: { id: "adaptive", name: "適応進化", type: "passive", stat: { all: 1.05 }, desc: "全能力+5%。" },
    mirror_skin: { id: "mirror_skin", name: "鏡皮膚", type: "passive", stat: { def: 1.1, thorns: 0.1 }, desc: "防御+10%、反射10%。" },
    child_heart: { id: "child_heart", name: "幼子の心", type: "passive", stat: { luck: 1.2, hp: 1.1 }, desc: "運・HP上昇。" },
    machine_core: { id: "machine_core", name: "機械コア", type: "passive", stat: { atk: 1.1, spd: 1.1 }, desc: "物攻・速度+10%。" },
    void_affinity: { id: "void_affinity", name: "虚無親和", type: "passive", stat: { anm: 1.25 }, desc: "異能+25%。" },
    bone_armor: { id: "bone_armor", name: "骨装甲", type: "passive", stat: { def: 1.2, hp: 1.05 }, desc: "防御+20%。" },
    time_dilation: { id: "time_dilation", name: "時間膨張", type: "passive", stat: { spd: 1.15 }, desc: "速度+15%。" },
    fire_immune: { id: "fire_immune", name: "炎耐性", type: "passive", stat: { def: 1.08 }, desc: "防御微増。" },
    ink_veil: { id: "ink_veil", name: "墨の帳", type: "passive", stat: { eva: 0.1 }, desc: "回避+10%。" },
    blood_pact: { id: "blood_pact", name: "血の契約", type: "passive", stat: { atk: 1.2, anm: 1.1 }, desc: "物攻・異能上昇。" },
    shadow_step: { id: "shadow_step", name: "影歩き", type: "passive", stat: { spd: 1.25, eva: 0.08 }, desc: "速度・回避上昇。" },
    sound_proof: { id: "sound_proof", name: "防音", type: "passive", stat: { def: 1.12 }, desc: "防御+12%。" },
    rust_aura: { id: "rust_aura", name: "錆のオーラ", type: "passive", stat: { anm: 1.08 }, onHit: "def_down", desc: "攻撃時に防御低下。" },
    pack_leader: { id: "pack_leader", name: "群れの長", type: "passive", stat: { atk: 1.1, spd: 1.05 }, desc: "物攻・速度微増。" },
    phase_body: { id: "phase_body", name: "位相体", type: "passive", stat: { eva: 0.15 }, desc: "回避+15%。" },
    gravity_well: { id: "gravity_well", name: "重力井戸", type: "passive", stat: { anm: 1.15, def: 1.05 }, desc: "異能・防御上昇。" },
    healer_touch: { id: "healer_touch", name: "癒しの手", type: "passive", stat: { regen: 0.02 }, desc: "毎ターンHP2%回復。" },
    fear_aura: { id: "fear_aura", name: "恐怖のオーラ", type: "passive", stat: { atk: 1.08 }, desc: "物攻微増。" },
    data_core: { id: "data_core", name: "データコア", type: "passive", stat: { luck: 1.15, anm: 1.05 }, desc: "運・異能上昇。" },
    containment_expert: { id: "containment_expert", name: "収容の専門家", type: "passive", stat: { def: 1.15, hp: 1.1 }, desc: "防御・HP上昇。" },
    cross_anomaly: { id: "cross_anomaly", name: "交差異常", type: "passive", stat: { all: 1.1 }, desc: "収容物体合成実験由来の全能力+10%。" },
    unique_snap: { id: "unique_snap", name: "彫刻の本能", type: "passive", unique: true, stat: { crit: 0.3, critDmg: 0.5 }, desc: "固有：クリ率+30%。" },
    unique_plague: { id: "unique_plague", name: "ペスト医の誓い", type: "passive", unique: true, stat: { anm: 1.3, regen: 0.02 }, desc: "固有：異能強化＋再生。" },
    unique_adapt: { id: "unique_adapt", name: "拒絶反応", type: "passive", unique: true, stat: { all: 1.15, regen: 0.05 }, desc: "固有：全能力+15%、高再生。" },
    unique_void: { id: "unique_void", name: "虚無の器", type: "passive", unique: true, stat: { anm: 1.4, eva: 0.12 }, desc: "固有：異能・回避大幅上昇。" },
    unique_why: { id: "unique_why", name: "なぜ？", type: "passive", unique: true, stat: { eva: 0.2, def: 1.2, hp: 1.1 }, desc: "固有：観測から外れる。回避・防御・HP上昇。" },
    unique_rebuild: { id: "unique_rebuild", name: "再構築プロトコル", type: "passive", unique: true, stat: { hp: 1.2, regen: 0.04 }, desc: "固有：HP上昇と再生。文明を立て直す。" },
    unique_solar: { id: "unique_solar", name: "太陽の姉妹", type: "passive", unique: true, stat: { luck: 1.4, eva: 0.1 }, desc: "固有：脅威を指差す。運・回避上昇。" },
    unique_glyph: { id: "unique_glyph", name: "歴史改変紋", type: "passive", unique: true, stat: { anm: 1.35, luck: 1.1 }, desc: "固有：壁画が記録を書き換える。" },
    unique_ward: { id: "unique_ward", name: "獄門", type: "passive", unique: true, stat: { def: 1.3, hp: 1.15 }, desc: "固有：死せる神を閉じ込める壁。" },
    unique_well: { id: "unique_well", name: "井戸の猫", type: "passive", unique: true, stat: { luck: 1.5, hp: 1.05 }, desc: "固有：そこに猫がいる、という確信。" },
    unique_toy: { id: "unique_toy", name: "思い出の玩具", type: "passive", unique: true, stat: { atk: 1.2, hp: 1.1 }, desc: "固有：掻き分けたくなる音。" },
    unique_rail: { id: "unique_rail", name: "存在しない路線", type: "passive", unique: true, stat: { spd: 1.3, eva: 0.08 }, desc: "固有：駅の隙間を走る。" },
    unique_gravity: { id: "unique_gravity", name: "重力吸収", type: "passive", unique: true, stat: { anm: 1.35, def: 1.1 }, desc: "固有：質量を吸い、圧を返す。" },
  },

  /** Catalog templates: base stats at Lv1 Rev0, class rank 1-4 */
  catalog: {
    scp173: { id: "scp173", scp: "SCP-173", name: "彫刻", class: "Euclid", rank: 2,
      base: { hp: 90, atk: 55, anm: 20, def: 40, spd: 70, luck: 25 },
      skills: ["snap_neck", "swift", "crit_master", "unique_snap"],
      look: "鉄筋コンクリートを削った人型彫刻。歪んだ顔に赤黒のスプレー、継ぎ目から鉄筋が覗く。",
      note: "視線を逸らすと接近する。収容物体合成実験では静止条件の研究が進む。" },
    scp096: { id: "scp096", scp: "SCP-096", name: "羞恥の男", class: "Euclid", rank: 3,
      base: { hp: 120, atk: 80, anm: 30, def: 35, spd: 45, luck: 15 },
      skills: ["rage_cry", "bash", "iron_will", "fear_aura"],
      look: "極度に痩せた白い人型。腕が異常に長く、顔は常に両手で覆われている。正面記録は禁止。",
      note: "顔を見られた者を執拗に追う。激怒時の戦力は計測不能。" },
    scp049: { id: "scp049", scp: "SCP-049", name: "ペスト医師", class: "Euclid", rank: 2,
      base: { hp: 75, atk: 30, anm: 60, def: 35, spd: 40, luck: 30 },
      skills: ["plague_touch", "heal_pulse", "plague_carrier", "unique_plague"],
      look: "中世のペスト医師装束。くちばしマスク、黒いローブ、革手袋。目元だけが暗い。",
      note: "「ペスト」を治療すると主張する。接触は要注意。" },
    scp682: { id: "scp682", scp: "SCP-682", name: "嫌悪するトカゲ", class: "Keter", rank: 4,
      base: { hp: 200, atk: 70, anm: 50, def: 60, spd: 30, luck: 10 },
      skills: ["regen_bulk", "bash", "adaptive", "unique_adapt"],
      look: "巨大な爬虫類様。皮膚は焼けただれ再生し、形状が不定。憎悪に満ちた黄色い目。",
      note: "あらゆる手段で生き延びる。収容物体合成実験の最難関素材。" },
    scp106: { id: "scp106", scp: "SCP-106", name: "腐った王", class: "Keter", rank: 3,
      base: { hp: 110, atk: 45, anm: 55, def: 50, spd: 35, luck: 20 },
      skills: ["rust_touch", "phase_shift", "rust_aura", "void_affinity"],
      look: "老人に見える人型。皮膚は黒く腐食し、粘液が滴る。周囲の金属が錆びていく。",
      note: "腐食の次元へ引きずり込む。隔離壁の定期点検必須。" },
    scp035: { id: "scp035", scp: "SCP-035", name: "魅惑の仮面", class: "Keter", rank: 3,
      base: { hp: 60, atk: 25, anm: 70, def: 25, spd: 50, luck: 40 },
      skills: ["cognito_hazard", "fear_gaze", "anomaly_amp", "lucky"],
      look: "白い陶器の演劇用仮面。表情が微かに変わり、内側から黒い腐食液が滲む。",
      note: "認知危害を伴う。装着者の精神を蝕む。" },
    scp079: { id: "scp079", scp: "SCP-079", name: "旧AI", class: "Euclid", rank: 2,
      base: { hp: 50, atk: 20, anm: 65, def: 30, spd: 55, luck: 35 },
      skills: ["data_mine", "info_siphon", "siphon_mastery", "artifact_hunter"],
      look: "1970年代のマイクロコンピュータ。緑のCRTに文章が流れ、筐体は埃をかぶる。",
      note: "1978年製のAI。ネットワーク隔離下で稼働。" },
    scp087: { id: "scp087", scp: "SCP-087", name: "階段", class: "Euclid", rank: 2,
      base: { hp: 80, atk: 35, anm: 45, def: 45, spd: 40, luck: 20 },
      skills: ["fear_gaze", "shadow_lunge", "shadow_step", "fear_aura"],
      look: "コンクリートの螺旋階段が闇の底へ続く。壁に薄い顔のような染みが浮かぶ。",
      note: "下へ続く階段。深層フロアの象徴。" },
    scp093: { id: "scp093", scp: "SCP-093", name: "赤い鏡", class: "Euclid", rank: 2,
      base: { hp: 70, atk: 30, anm: 55, def: 40, spd: 45, luck: 30 },
      skills: ["mirror_blast", "cognito_hazard", "mirror_skin", "anomaly_amp"],
      look: "赤みがかった円盤状の鏡。裏面に未知の記号が刻まれ、反射が現実とわずかにずれる。",
      note: "鏡越しの異世界への入口。平行次元探索に利用。" },
    scp131: { id: "scp131", scp: "SCP-131", name: "アイドリング", class: "Safe", rank: 1,
      base: { hp: 55, atk: 15, anm: 25, def: 30, spd: 60, luck: 45 },
      skills: ["docile_aura", "heal_pulse", "docile_nature", "swift"],
      look: "目玉にキャタピラが付いた小型生物。オレンジと青の個体が並び、人を見上げる。",
      note: "従順で人懐っこい。新人研究員のモラル維持に寄与。" },
    scp294: { id: "scp294", scp: "SCP-294", name: "コーヒーマシン", class: "Euclid", rank: 2,
      base: { hp: 60, atk: 20, anm: 40, def: 35, spd: 30, luck: 50 },
      skills: ["candy_offer", "heal_pulse", "lucky", "docile_nature"],
      look: "コーヒーショップ風の飲料機。金属筐体とキーボード。カップ受けに湯気が立つ。",
      note: "任意の飲料を排出。成分は要分析。" },
    scp500: { id: "scp500", scp: "SCP-500", name: "万能薬", class: "Safe", rank: 1,
      base: { hp: 40, atk: 10, anm: 30, def: 25, spd: 35, luck: 40 },
      skills: ["heal_pulse", "regen_passive", "healer_touch", "docile_nature"],
      look: "赤いカプセル錠剤が詰まった小さなプラスチックボトル。ラベルは剥がれている。",
      note: "1錠で全疾患を治療。在庫は極めて限定。" },
    scp999: { id: "scp999", scp: "SCP-999", name: "ティックルモンスター", class: "Safe", rank: 1,
      base: { hp: 80, atk: 10, anm: 35, def: 35, spd: 40, luck: 55 },
      skills: ["candy_offer", "docile_aura", "child_heart", "regen_passive"],
      look: "橙色の不定形スライム。半透明で温かく、笑っているような窪みが顔になる。",
      note: "接触すると極度の幸福感。モラル回復の要。" },
    scp914: { id: "scp914", scp: "SCP-914", name: "時計仕掛けの装置", class: "Safe", rank: 2,
      base: { hp: 100, atk: 25, anm: 50, def: 50, spd: 20, luck: 35 },
      skills: ["reclassify", "data_mine", "machine_core", "containment_expert"],
      look: "部屋を占有する巨大な黄銅の時計仕掛け。投入箱・排出箱と粗製〜超精のダイヤル。",
      note: "投入物を精製・粗製化。錬金の基盤装置。" },
    scp055: { id: "scp055", scp: "SCP-055", name: "記憶不能", class: "Keter", rank: 3,
      base: { hp: 70, atk: 30, anm: 60, def: 45, spd: 55, luck: 25 },
      skills: ["phase_shift", "cognito_hazard", "phase_body", "shadow_step"],
      look: "記録写真では球体にも立方体にも見える。輪郭が定まらず、見るたびに形が違う。",
      note: "記憶できない。記録すら困難。" },
    scp073: { id: "scp073", scp: "SCP-073", name: "Cain", class: "Euclid", rank: 3,
      base: { hp: 100, atk: 50, anm: 40, def: 55, spd: 45, luck: 30 },
      skills: ["mirror_blast", "shield_wall", "mirror_skin", "iron_will"],
      look: "中東系の男性。額に傷、白いシャツ。触れた植物は枯れ、肌は損傷を反射する。",
      note: "攻撃を反射する。名前の響きに注意。" },
    scp076: { id: "scp076", scp: "SCP-076", name: "Abel", class: "Keter", rank: 4,
      base: { hp: 130, atk: 85, anm: 40, def: 40, spd: 65, luck: 20 },
      skills: ["teleport_strike", "slash", "predator", "crit_master"],
      look: "筋肉質の男性。黒い目、短い黒髪。石棺の前で物質化した黒い刃を持つ。",
      note: "石棺から復活する戦闘体。単体戦闘力最高クラス。" },
    scp085: { id: "scp085", scp: "SCP-085", name: "Cassy", class: "Safe", rank: 1,
      base: { hp: 45, atk: 20, anm: 35, def: 20, spd: 70, luck: 40 },
      skills: ["shadow_lunge", "phase_shift", "swift", "phase_body"],
      look: "鉛筆で描かれた若い女性。白い画用紙の二次元世界に閉じ込められ、線だけで存在する。",
      note: "2次元存在。紙面上を移動する。" },
    scp113: { id: "scp113", scp: "SCP-113", name: "性別転換リング", class: "Safe", rank: 1,
      base: { hp: 50, atk: 25, anm: 45, def: 30, spd: 50, luck: 35 },
      skills: ["reclassify", "luck_drain", "lucky", "anomaly_amp"],
      look: "赤みがかった小さな金属円盤。指輪のように見えるが、表面に微細な結晶構造。",
      note: "接触で性別が変化。実験データは蓄積中。" },
    scp178: { id: "scp178", scp: "SCP-178", name: "3D眼鏡", class: "Euclid", rank: 2,
      base: { hp: 55, atk: 25, anm: 50, def: 30, spd: 45, luck: 30 },
      skills: ["cognito_hazard", "fear_gaze", "anomaly_amp", "fear_aura"],
      look: "白黒の段ボール製3D立体眼鏡。レンズ越しに別層の輪郭がにじむ。",
      note: "着用者に異次元の存在を視認させる。" },
    scp231: { id: "scp231", scp: "SCP-231", name: "特別収容手順", class: "Keter", rank: 4,
      base: { hp: 60, atk: 20, anm: 80, def: 30, spd: 35, luck: 15 },
      skills: ["containment_field", "shield_wall", "containment_expert", "iron_will"],
      look: "重密封の収容扉と警告ストライプ。対象の姿は記録せず、手順書だけが残る。",
      note: "収容手順の厳守が世界の存続に関わる。詳細は Level 4 以上。" },
    scp239: { id: "scp239", scp: "SCP-239", name: "ウィッチ・チャイルド", class: "Keter", rank: 3,
      base: { hp: 65, atk: 25, anm: 75, def: 25, spd: 40, luck: 35 },
      skills: ["anomaly_burst", "gravity_crush", "gravity_well", "anomaly_amp"],
      look: "観測窓の曇りガラス越しに、小さな魔女帽と現実の歪みが光る。顔は記録しない。",
      note: "信じたことが現実になる。認知遮断下で収容。" },
    scp343: { id: "scp343", scp: "SCP-343", name: "神", class: "Safe", rank: 4,
      base: { hp: 150, atk: 40, anm: 70, def: 60, spd: 40, luck: 60 },
      skills: ["heal_pulse", "shield_wall", "healer_touch", "containment_expert"],
      look: "白い髭の穏やかな老人。部屋の調度は本人の意思で変わり、光が柔らかい。",
      note: "全知全能を主張。実態は未解明。" },
    scp354: { id: "scp354", scp: "SCP-354", name: "赤い池", class: "Keter", rank: 3,
      base: { hp: 100, atk: 40, anm: 60, def: 45, spd: 30, luck: 20 },
      skills: ["blood_rite", "anomaly_burst", "blood_pact", "plague_carrier"],
      look: "不透明な真っ赤な池。岸は焦げた土で、時折水面が生き物のように膨らむ。",
      note: "池から異形が出現。深層探索の終点候補。" },
    scp426: { id: "scp426", scp: "SCP-426", name: "トースター", class: "Euclid", rank: 1,
      base: { hp: 50, atk: 30, anm: 25, def: 40, spd: 25, luck: 30 },
      skills: ["bash", "hardened", "iron_will", "thorns"],
      look: "ごく普通の家庭用トースター。クローム筐体。記録者は一人称で「私」と呼ぶ。",
      note: "認知危害：自分がトースターだと思い込む。" },
    scp457: { id: "scp457", scp: "SCP-457", name: "火の人", class: "Euclid", rank: 2,
      base: { hp: 80, atk: 45, anm: 50, def: 30, spd: 50, luck: 20 },
      skills: ["fire_breath", "bash", "fire_immune", "predator"],
      look: "人型にまとまった炎。核は白い熱源、輪郭は揺らめき、床を焦がす。",
      note: "炎で構成された人型。可燃物の近くに置かない。" },
    scp529: { id: "scp529", scp: "SCP-529", name: "ジョスィー", class: "Safe", rank: 1,
      base: { hp: 50, atk: 20, anm: 20, def: 25, spd: 55, luck: 40 },
      skills: ["pack_howl", "slash", "pack_leader", "swift"],
      look: "茶トラの猫の前半身だけ。断面はなめらかで出血せず、後半は存在しない。",
      note: "前半身のみの猫。後方は存在しない。" },
    scp650: { id: "scp650", scp: "SCP-650", name: "スターター", class: "Euclid", rank: 2,
      base: { hp: 75, atk: 35, anm: 40, def: 35, spd: 60, luck: 25 },
      skills: ["fear_gaze", "shadow_lunge", "shadow_step", "fear_aura"],
      look: "黒い人型彫刻。腕を広げた威嚇ポーズ。観察外で位置と姿勢を変える。",
      note: "背後に立って怖がらせる。実害は少ない。" },
    scp860: { id: "scp860", scp: "SCP-860", name: "青い鍵", class: "Safe", rank: 1,
      base: { hp: 45, atk: 20, anm: 35, def: 30, spd: 45, luck: 35 },
      skills: ["phase_shift", "shadow_lunge", "phase_body", "swift"],
      look: "青い金属の鍵。歯に森の文様が彫刻され、冷たい光を帯びる。",
      note: "特定の扉を開く。森への入口。" },
    scp895: { id: "scp895", scp: "SCP-895", name: "カメラのない監視", class: "Euclid", rank: 2,
      base: { hp: 60, atk: 25, anm: 50, def: 35, spd: 40, luck: 30 },
      skills: ["cognito_hazard", "fear_gaze", "data_mine", "fear_aura"],
      look: "古いオークの棺。暗い地下室。カメラを向けると映像が崩壊する。",
      note: "視聴者に幻覚を誘発。監視カメラは使用禁止。" },
    scp939: { id: "scp939", scp: "SCP-939", name: "声なき者", class: "Keter", rank: 3,
      base: { hp: 95, atk: 60, anm: 35, def: 40, spd: 55, luck: 25 },
      skills: ["pack_howl", "slash", "predator", "pack_leader"],
      look: "赤褐色の皮膚、目がなく牙の列だけが口を埋める。後肢で立つ四足の捕食者。",
      note: "声を模倣して獲物を誘う。群れで行動。" },
    scp966: { id: "scp966", scp: "SCP-966", name: "眠れなくする者", class: "Euclid", rank: 2,
      base: { hp: 70, atk: 40, anm: 45, def: 35, spd: 50, luck: 30 },
      skills: ["mass_siphon", "shadow_lunge", "open_siphon", "super_lucky"],
      look: "可視光ではほぼ透明の人型。赤外で長い爪と細い輪郭だけが浮かぶ。",
      note: "可視光不可。対象の睡眠を阻害。情報吸い上げの開幕役。" },
    scp5000: { id: "scp5000", scp: "SCP-5000", name: "なぜ？", class: "Keter", rank: 4,
      base: { hp: 140, atk: 50, anm: 45, def: 70, spd: 40, luck: 18 },
      skills: ["phase_shift", "containment_field", "iron_will", "unique_why"],
      look: "黒く傷んだ財団製の戦闘スーツ。バイザー付き外骨格で、側面に記録媒体用のポートがある。着用者は記録しない。",
      note: "疼痛を遮断し身体を強化する。観測から外れる性質あり。詳細は Level 4 以上。" },
    scp2000: { id: "scp2000", scp: "SCP-2000", name: "デウス・エクス・マキナ", class: "Thaumiel", rank: 4,
      base: { hp: 160, atk: 38, anm: 55, def: 68, spd: 24, luck: 32 },
      skills: ["heal_pulse", "reclassify", "containment_expert", "unique_rebuild"],
      look: "地下の巨大な再構築施設。円環の機械ホールと休眠する複製槽が岩盤の下に続く。",
      note: "文明崩壊後の再起動装置。Thaumiel運用の中核。" },
    scp179: { id: "scp179", scp: "SCP-179", name: "太陽の姉妹", class: "Thaumiel", rank: 4,
      base: { hp: 88, atk: 22, anm: 78, def: 38, spd: 52, luck: 58 },
      skills: ["fear_gaze", "anomaly_burst", "lucky", "unique_solar"],
      look: "太陽の南極付近に浮かぶ人型。炭色の肌に金の天体紋、髪が太陽風のように流れる。",
      note: "接近する脅威を指差して警告する。財団の宇宙監視に不可欠。" },
    scp2140: { id: "scp2140", scp: "SCP-2140", name: "洞窟壁画", class: "Thaumiel", rank: 3,
      base: { hp: 72, atk: 18, anm: 82, def: 32, spd: 34, luck: 42 },
      skills: ["cognito_hazard", "info_siphon", "anomaly_amp", "unique_glyph"],
      look: "黄土と炭で描かれた古紋の石板。見る者の履歴を都合のよい記録へ書き換える。",
      note: "歴史改変型の認知危害。閲覧は接種済み職員に限る。" },
    scp2932: { id: "scp2932", scp: "SCP-2932", name: "死せる神の監獄", class: "Thaumiel", rank: 4,
      base: { hp: 185, atk: 32, anm: 52, def: 82, spd: 18, luck: 14 },
      skills: ["containment_field", "shield_wall", "bone_armor", "unique_ward"],
      look: "黒石と青銅の同心円門。死んだ神格を閉じ込める地下牢の入口。",
      note: "収容そのものが異常。門を維持することが戦力になる。" },
    scp040jp: { id: "scp040jp", scp: "SCP-040-JP", name: "ねこですよろしくおねがいします", class: "Safe", rank: 1,
      base: { hp: 58, atk: 10, anm: 28, def: 32, spd: 36, luck: 62 },
      skills: ["docile_aura", "candy_offer", "lucky", "unique_well"],
      look: "鎖のかかった木造の井戸小屋。中を直接見ると「そこに猫がいる」と確信する。",
      note: "視認型の認識災害。カメラ越しなら実体は観測されない。" },
    scp173jp: { id: "scp173jp", scp: "SCP-173-JP", name: "恐竜—イミテーション", class: "Euclid", rank: 2,
      base: { hp: 96, atk: 52, anm: 24, def: 42, spd: 38, luck: 28 },
      skills: ["pack_howl", "bash", "predator", "unique_toy"],
      look: "日本製の玩具が寄り集まって戯画の恐竜になる。音を聞くと中へ掻き分けたくなる。",
      note: "防音室必須。録音なら影響しない。" },
    scp023jp: { id: "scp023jp", scp: "SCP-023-JP", name: "影の鉄道路線", class: "Keter", rank: 3,
      base: { hp: 84, atk: 44, anm: 48, def: 34, spd: 62, luck: 24 },
      skills: ["shadow_lunge", "phase_shift", "shadow_step", "unique_rail"],
      look: "駅に増設された、本来ない階段と封鎖工事の仮囲い。その先に存在しない路線がある。",
      note: "国内の駅へ不規則に干渉する。完全封鎖は困難。" },
    scp870jp: { id: "scp870jp", scp: "SCP-870-JP", name: "重力を吸う黒球", class: "Keter", rank: 4,
      base: { hp: 102, atk: 28, anm: 86, def: 48, spd: 28, luck: 18 },
      skills: ["gravity_crush", "void_pull", "gravity_well", "unique_gravity"],
      look: "直径約3cmの真っ黒な球。近づくものを吸い、ゆっくり降下する。サイト-8186で収容。",
      note: "重力そのものを吸収すると推定。実験凍結中。" },
    // --- Cross-test hybrids (8) ---
    x049_173: { id: "x049_173", scp: "SCP-Unknown-049173", name: "彫刻医", class: "Euclid", rank: 3, hybrid: ["scp049", "scp173"],
      base: { hp: 100, atk: 50, anm: 55, def: 45, spd: 55, luck: 28 },
      skills: ["plague_touch", "snap_neck", "plague_carrier", "cross_anomaly"],
      look: "ペスト医師のローブを纏ったコンクリート彫刻。くちばしと歪んだ顔が一体化している。",
      note: "収容物体合成実験049×173。静止時に疫病を撒く彫刻。" },
    x914_682: { id: "x914_682", scp: "SCP-Unknown-914682", name: "精製トカゲ", class: "Keter", rank: 4, hybrid: ["scp914", "scp682"],
      base: { hp: 180, atk: 65, anm: 55, def: 55, spd: 28, luck: 12 },
      skills: ["regen_bulk", "reclassify", "adaptive", "cross_anomaly"],
      look: "黄銅の歯車が皮膚に埋め込まれた爬虫類。精製された金属光沢と再生する肉が混在する。",
      note: "収容物体合成実験914×682。精製された適応生物。" },
    x096_076: { id: "x096_076", scp: "SCP-Unknown-096076", name: "怒りの刃", class: "Keter", rank: 4, hybrid: ["scp096", "scp076"],
      base: { hp: 140, atk: 90, anm: 35, def: 38, spd: 55, luck: 15 },
      skills: ["rage_cry", "teleport_strike", "predator", "cross_anomaly"],
      look: "白い極度に痩せた体。顔は腕で隠し、物質化した黒い刃を持つ。正面記録は禁止。",
      note: "収容物体合成実験096×076。激怒と転移を併せ持つ。" },
    x131_999: { id: "x131_999", scp: "SCP-Unknown-131999", name: "癒しの双輪", class: "Safe", rank: 2, hybrid: ["scp131", "scp999"],
      base: { hp: 90, atk: 12, anm: 30, def: 38, spd: 50, luck: 50 },
      skills: ["candy_offer", "docile_aura", "child_heart", "cross_anomaly"],
      look: "橙色スライムの上に目玉キャタピラが乗っている。どちらも人を見て喜んでいる。",
      note: "収容物体合成実験131×999。モラル回復の決定版。" },
    x079_914: { id: "x079_914", scp: "SCP-Unknown-079914", name: "精製AI", class: "Euclid", rank: 3, hybrid: ["scp079", "scp914"],
      base: { hp: 55, atk: 22, anm: 70, def: 35, spd: 50, luck: 40 },
      skills: ["data_mine", "reclassify", "machine_core", "cross_anomaly"],
      look: "時計仕掛けの黄銅筐体に緑のCRT。歯車が回りながら文字が流れる。",
      note: "収容物体合成実験079×914。精製された知能体。" },
    x035_178: { id: "x035_178", scp: "SCP-Unknown-035178", name: "認知の仮面", class: "Keter", rank: 4, hybrid: ["scp035", "scp178"],
      base: { hp: 65, atk: 28, anm: 80, def: 28, spd: 48, luck: 38 },
      skills: ["cognito_hazard", "fear_gaze", "anomaly_amp", "cross_anomaly"],
      look: "白い仮面に3D眼鏡が食い込んでいる。レンズの奥に別層の目が複数浮かぶ。",
      note: "収容物体合成実験035×178。認知危害の複合。" },
    x294_500: { id: "x294_500", scp: "SCP-Unknown-294500", name: "万能ドリンク", class: "Safe", rank: 2, hybrid: ["scp294", "scp500"],
      base: { hp: 50, atk: 12, anm: 35, def: 28, spd: 32, luck: 48 },
      skills: ["heal_pulse", "candy_offer", "healer_touch", "cross_anomaly"],
      look: "飲料機から赤い万能薬の液体がカップに注がれている。湯気は甘い薬品の匂い。",
      note: "収容物体合成実験294×500。任意の治癒飲料。" },
    x939_966: { id: "x939_966", scp: "SCP-Unknown-939966", name: "夜の狩人", class: "Keter", rank: 3, hybrid: ["scp939", "scp966"],
      base: { hp: 85, atk: 55, anm: 40, def: 38, spd: 58, luck: 28 },
      skills: ["pack_howl", "shadow_lunge", "predator", "cross_anomaly"],
      look: "半透明の赤褐色捕食者。目はなく、牙と長い爪だけが赤外で光る。",
      note: "収容物体合成実験939×966。夜間の群れ狩り。" },
    x073_076: { id: "x073_076", scp: "SCP-Unknown-073076", name: "兄弟の刃", class: "Keter", rank: 4, hybrid: ["scp073", "scp076"],
      base: { hp: 130, atk: 88, anm: 32, def: 48, spd: 50, luck: 16 },
      skills: ["teleport_strike", "slash", "predator", "cross_anomaly"],
      look: "青銅の肌に印を焼かれた成人。物質化した黒い刃を持ち、もう一方の腕にも対になる印がある。",
      note: "収容物体合成実験073×076。兄弟の対立が一つの刃になる。" },
    x106_895: { id: "x106_895", scp: "SCP-Unknown-106895", name: "腐食の棺", class: "Keter", rank: 3, hybrid: ["scp106", "scp895"],
      base: { hp: 100, atk: 40, anm: 58, def: 52, spd: 32, luck: 18 },
      skills: ["rust_touch", "phase_shift", "rust_aura", "cross_anomaly"],
      look: "オークの棺が錆びた鋼壁を半分貫いている。黒い残渣が金属を溶かす。蓋は閉じたまま。",
      note: "収容物体合成実験106×895。監視映像は崩壊する。" },
    x457_354: { id: "x457_354", scp: "SCP-Unknown-457354", name: "紅蓮の池人", class: "Keter", rank: 3, hybrid: ["scp457", "scp354"],
      base: { hp: 95, atk: 48, anm: 62, def: 36, spd: 40, luck: 22 },
      skills: ["fire_breath", "anomaly_burst", "fire_immune", "cross_anomaly"],
      look: "赤い液面の縁に立つ炎の人型。池の光がコンクリートを濡らす。",
      note: "収容物体合成実験457×354。火と赤い池が同居する。" },
    x087_860: { id: "x087_860", scp: "SCP-Unknown-087860", name: "鍵の階段", class: "Euclid", rank: 3, hybrid: ["scp087", "scp860"],
      base: { hp: 78, atk: 30, anm: 50, def: 42, spd: 44, luck: 28 },
      skills: ["void_pull", "phase_shift", "time_dilation", "cross_anomaly"],
      look: "無限に下りるコンクリート階段。一段の上で青い鍵が浮かんでいる。",
      note: "収容物体合成実験087×860。鍵は森ではなく深層へ開く。" },
    x343_914: { id: "x343_914", scp: "SCP-Unknown-343914", name: "精製された神", class: "Safe", rank: 4, hybrid: ["scp343", "scp914"],
      base: { hp: 110, atk: 28, anm: 70, def: 45, spd: 36, luck: 48 },
      skills: ["heal_pulse", "reclassify", "healer_touch", "cross_anomaly"],
      look: "黄金の光を帯びた老人に、黄銅の歯車と文字盤が埋め込まれている。部屋の家具が微かに組み変わる。",
      note: "収容物体合成実験343×914。神性を914が精製した。" },
    x055_079: { id: "x055_079", scp: "SCP-Unknown-055079", name: "忘れられた機械", class: "Keter", rank: 3, hybrid: ["scp055", "scp079"],
      base: { hp: 52, atk: 18, anm: 72, def: 30, spd: 48, luck: 38 },
      skills: ["data_mine", "info_siphon", "siphon_mastery", "cross_anomaly"],
      look: "1970年代のCRT。緑の燐光が球とも立方体ともつかない形を描き、見終えると内容を忘れる。",
      note: "収容物体合成実験055×079。記録できない知能。" },
    x2000_914: { id: "x2000_914", scp: "SCP-Unknown-2000914", name: "精製再構築機", class: "Thaumiel", rank: 4, hybrid: ["scp2000", "scp914"],
      base: { hp: 150, atk: 36, anm: 60, def: 62, spd: 26, luck: 34 },
      skills: ["reclassify", "heal_pulse", "machine_core", "cross_anomaly"],
      look: "再構築ホールが黄銅の時計機構になった地下。歯車の隙間から複製槽の灯が漏れる。",
      note: "収容物体合成実験2000×914。文明再生を精密化した。" },
    x040jp_131: { id: "x040jp_131", scp: "SCP-Unknown-040JP131", name: "井戸の双瞳", class: "Safe", rank: 2, hybrid: ["scp040jp", "scp131"],
      base: { hp: 70, atk: 12, anm: 28, def: 34, spd: 42, luck: 58 },
      skills: ["docile_aura", "candy_offer", "child_heart", "cross_anomaly"],
      look: "井戸の縁にオレンジの目玉キャタピラが二体、暗闇を覗き込んでいる。小屋に猫はいない。",
      note: "収容物体合成実験040-JP×131。見てしまいたくなる井戸。" },
  },

  /**
   * 回収等級。オブジェクトクラスとは別軸だが、色は classColors と共有して画面の一貫性を保つ。
   */
  rarities: {
    E: { id: "E", name: "汎用", color: "#9aa0a8" },
    D: { id: "D", name: "鉄", color: "#8a8f96" },
    C: { id: "C", name: "銅", color: "#c47a3a" },
    B: { id: "B", name: "銀", color: "#c5c9d1" },
    A: { id: "A", name: "金", color: "#e0b84a" },
    S: { id: "S", name: "虹", color: "#e07ad3" },
    SS: { id: "SS", name: "プリズム", color: "#ffffff" },
  },

  /** アタッチ個体のレア抽選。SS はアイテムと同じパラレル背景 */
  attachRarityWeights: { E: 10, D: 24, C: 26, B: 20, A: 12, S: 6, SS: 2 },

  /** 倉庫の初期容量。拠点強化で拡張できるよう state 側に複製する */
  storageDefaults: {
    slots: 200,
    partStack: 9999,
    itemStack: 10,
  },

  /** 分解でクラフト材料の何割が戻るか（切り捨て・最低1） */
  dismantleRate: 0.6,

  /**
   * 基礎部品8種。T1(4) → T2(2) → T3(2)。
   * 倉庫本体とは別枠（常時横8）に置く。分解は不可（部品を部品にはできない）。
   */
  parts: [
    { id: "p_scrap", name: "金属片", tier: 1, rarity: "E", value: 2 },
    { id: "p_wire", name: "導線", tier: 1, rarity: "E", value: 2 },
    { id: "p_resin", name: "樹脂", tier: 1, rarity: "E", value: 3 },
    { id: "p_tissue", name: "有機組織", tier: 1, rarity: "E", value: 4 },
    { id: "p_alloy", name: "合金板", tier: 2, rarity: "D", value: 14, craft: { p_scrap: 4, p_resin: 2 } },
    { id: "p_circuit", name: "回路基板", tier: 2, rarity: "D", value: 18, craft: { p_wire: 4, p_resin: 2 } },
    { id: "p_cell", name: "電源セル", tier: 3, rarity: "C", value: 70, craft: { p_alloy: 2, p_circuit: 2 } },
    { id: "p_anomalon", name: "異常粒子", tier: 3, rarity: "C", value: 120, craft: { p_tissue: 2, p_circuit: 2, p_resin: 4 } },
  ],

  /** 廃止部品 → 現行部品（旧セーブ移行用） */
  partAlias: { p_glass: "p_resin", p_reagent: "p_tissue" },

  /**
   * 深度ごとに出る部品。深層ほど上位ティアが混ざるが、
   * weight を下げて価値差（金属片2 vs 異常粒子120）に見合う出現率にする。
   */
  partDropTable: [
    { minDepth: 1, weight: 6, ids: ["p_scrap", "p_wire", "p_resin", "p_tissue"] },
    { minDepth: 10, weight: 3, ids: ["p_alloy", "p_circuit"] },
    { minDepth: 25, weight: 1, ids: ["p_cell", "p_anomalon"] },
  ],

  /** Drop/recovery objects for cataloging（収容アイテム。スタック上限は itemStack） */
  recoveryObjects: [
    { id: "obj_wire", name: "銅線", rarity: "E", value: 8, bonus: { atk: 3 },
      scrapTo: { p_wire: 3, p_scrap: 1 } },
    { id: "obj_bone", name: "骨片", rarity: "E", value: 10, bonus: { def: 5 },
      scrapTo: { p_tissue: 2, p_scrap: 1 } },
    { id: "obj_ash", name: "灰", rarity: "E", value: 10, bonus: { atk: 4 },
      scrapTo: { p_tissue: 2, p_resin: 1 } },
    { id: "obj_paper", name: "落書き紙", rarity: "E", value: 12, bonus: { spd: 5 },
      scrapTo: { p_resin: 2, p_tissue: 1 } },
    { id: "obj_gear", name: "時計仕掛け部品", rarity: "D", value: 26, bonus: { spd: 3 },
      scrapTo: { p_alloy: 1, p_scrap: 3 }, craft: { p_alloy: 2, p_scrap: 5 }, craftCost: 20 },
    { id: "obj_ink", name: "墨汁", rarity: "D", value: 28, bonus: { anm: 3 },
      scrapTo: { p_tissue: 3, p_resin: 1 }, craft: { p_tissue: 6, p_resin: 2 }, craftCost: 22 },
    { id: "obj_mirror", name: "割れた鏡", rarity: "D", value: 30, bonus: { luck: 5 },
      scrapTo: { p_resin: 4, p_alloy: 1 }, craft: { p_resin: 7, p_alloy: 2 }, craftCost: 25 },
    { id: "obj_fur", name: "三毛の毛", rarity: "D", value: 32, bonus: { spd: 4 },
      scrapTo: { p_tissue: 5 }, craft: { p_tissue: 9 }, craftCost: 28 },
    { id: "obj_blood", name: "異常血液サンプル", rarity: "C", value: 60, bonus: { anm: 5 },
      scrapTo: { p_tissue: 4, p_anomalon: 1 }, craft: { p_tissue: 6, p_anomalon: 2 }, craftCost: 50 },
    { id: "obj_pill", name: "赤い錠剤", rarity: "C", value: 68, bonus: { hp: 10 },
      scrapTo: { p_tissue: 5, p_anomalon: 1 }, craft: { p_tissue: 8, p_anomalon: 2 }, craftCost: 55 },
    { id: "obj_key", name: "青い鍵の欠片", rarity: "C", value: 75, bonus: { luck: 6 },
      scrapTo: { p_alloy: 2, p_cell: 1 }, craft: { p_alloy: 3, p_cell: 2 }, craftCost: 60 },
    { id: "obj_candy", name: "不明の飴", rarity: "B", value: 140, bonus: { luck: 8 },
      scrapTo: { p_anomalon: 2, p_cell: 1 }, craft: { p_anomalon: 3, p_cell: 2 }, craftCost: 120 },
    { id: "obj_ofuda", name: "井戸の御札", rarity: "B", value: 150, bonus: { luck: 7 },
      scrapTo: { p_resin: 4, p_tissue: 2 }, craft: { p_resin: 7, p_tissue: 4 }, craftCost: 110 },
    { id: "obj_railspike", name: "影路線の犬釘", rarity: "B", value: 155, bonus: { spd: 6 },
      scrapTo: { p_alloy: 2, p_scrap: 4 }, craft: { p_alloy: 4, p_scrap: 6 }, craftCost: 115 },
    { id: "obj_toyfang", name: "恐竜玩具の牙", rarity: "C", value: 72, bonus: { atk: 6 },
      scrapTo: { p_resin: 5, p_tissue: 2 }, craft: { p_resin: 8, p_tissue: 3 }, craftCost: 58 },
    { id: "obj_seed", name: "再構築種子", rarity: "A", value: 280, bonus: { hp: 16 },
      scrapTo: { p_anomalon: 3, p_cell: 2 }, craft: { p_anomalon: 5, p_cell: 3, obj_pill: 1 }, craftCost: 240 },
    { id: "obj_solar", name: "太陽の鱗片", rarity: "A", value: 300, bonus: { luck: 12 },
      scrapTo: { p_anomalon: 3, p_alloy: 2 }, craft: { p_anomalon: 5, p_alloy: 3, obj_mirror: 1 }, craftCost: 260 },
    { id: "obj_glyph", name: "壁画破片", rarity: "A", value: 290, bonus: { anm: 12 },
      scrapTo: { p_resin: 6, p_anomalon: 2 }, craft: { p_resin: 10, p_anomalon: 3, obj_ink: 1 }, craftCost: 250 },
    { id: "obj_wardlock", name: "獄門錠", rarity: "A", value: 310, bonus: { def: 14 },
      scrapTo: { p_alloy: 4, p_cell: 2 }, craft: { p_alloy: 7, p_cell: 3, obj_key: 1 }, craftCost: 270 },
    { id: "obj_voidorb", name: "重力黒球の殻", rarity: "S", value: 520, bonus: { anm: 18 },
      scrapTo: { p_anomalon: 6, p_cell: 3 }, craft: { p_anomalon: 10, p_cell: 5, obj_wardlock: 1 }, craftCost: 480 },
  ],

  artifacts: [
    { id: "art_shield", name: "隔離シールド", slot: "accessory", gear: "armor", rarity: "B", stat: { def: 15, hp: 20 }, sell: 500,
      skill: { name: "隔離壁", desc: "展開部隊の防御を底上げする。" },
      scrapTo: { p_alloy: 6, p_cell: 2 }, craft: { p_alloy: 10, p_cell: 3 }, craftCost: 200 },
    { id: "art_lens", name: "分析レンズ", slot: "accessory", gear: "head", rarity: "B", stat: { luck: 20, anm: 10 }, sell: 800,
      skill: { name: "解析光", desc: "運と異能を同時に伸ばす。" },
      scrapTo: { p_resin: 12, p_circuit: 4, p_cell: 2 }, craft: { p_resin: 20, p_circuit: 7, p_cell: 3 }, craftCost: 300 },
    { id: "art_blade", name: "異能刃", slot: "weapon", gear: "mainWeapon", weaponType: "blade", rarity: "B", stat: { atk: 25, crit: 0.1 }, sell: 1200,
      skill: { name: "異能切断", desc: "物攻とクリティカルを伸ばす。" },
      scrapTo: { p_alloy: 8, p_anomalon: 3 }, craft: { p_alloy: 13, p_anomalon: 5 }, craftCost: 500 },
    { id: "art_core", name: "反応炉コア", slot: "accessory", gear: "accessory", rarity: "A", stat: { anm: 20, atk: 10 }, sell: 1500,
      scrapTo: { p_cell: 6, p_circuit: 6 }, craft: { p_cell: 10, p_circuit: 10 }, craftCost: 800 },
    { id: "art_amulet", name: "再分類の護符", slot: "accessory", gear: "accessory", rarity: "A", stat: { all: 5 }, sell: 2000,
      scrapTo: { p_anomalon: 8, p_cell: 4 }, craft: { p_anomalon: 13, p_cell: 7 }, craftCost: 1200 },
    { id: "art_void", name: "虚無の欠片", slot: "weapon", gear: "subWeapon", rarity: "S", stat: { anm: 30, eva: 0.05 }, sell: 3000,
      skill: { name: "虚無侵食", desc: "異能と回避を同時に稼ぐ。" },
      scrapTo: { p_anomalon: 14, p_cell: 6 }, craft: { p_anomalon: 22, p_cell: 10 }, craftCost: 2000 },
    { id: "art_thaumiel", name: "Thaumiel認可証", slot: "accessory", gear: "accessory", rarity: "SS", stat: { all: 10, luck: 15 }, sell: 5000,
      skill: { name: "Thaumiel認可", desc: "全能力を底上げし、収容運用を安定させる。" },
      scrapTo: { p_anomalon: 24, p_cell: 12 }, craft: { p_anomalon: 38, p_cell: 20 }, craftCost: 4000 },
    { id: "art_seedcore", name: "再構築コア", slot: "accessory", gear: "accessory", rarity: "S", stat: { hp: 28, regen: 0.02 }, sell: 3200,
      skill: { name: "再構築", desc: "損傷した編成を立て直す核。" },
      scrapTo: { p_anomalon: 10, p_cell: 6 }, craft: { p_anomalon: 16, p_cell: 8, obj_seed: 1 }, craftCost: 2200 },
    { id: "art_solarring", name: "太陽の指輪", slot: "accessory", gear: "accessory", rarity: "S", stat: { luck: 25, anm: 12 }, sell: 3400,
      skill: { name: "警告の指", desc: "運と異能を同時に伸ばす。" },
      scrapTo: { p_anomalon: 8, p_alloy: 6 }, craft: { p_anomalon: 14, p_alloy: 8, obj_solar: 1 }, craftCost: 2300 },
    { id: "art_voidcloak", name: "虚無の外套", slot: "accessory", gear: "clothes", rarity: "A", stat: { eva: 0.08, def: 12 }, sell: 1800,
      skill: { name: "認知遮蔽", desc: "輪郭を溶かし被弾を減らす。" },
      scrapTo: { p_resin: 16, p_anomalon: 4 }, craft: { p_resin: 24, p_anomalon: 6, obj_ofuda: 1 }, craftCost: 900 },
    { id: "art_tread", name: "位相の靴底", slot: "accessory", gear: "shoes", rarity: "A", stat: { spd: 16, eva: 0.04 }, sell: 1600,
      skill: { name: "位相歩行", desc: "床を半歩ずれて移動する。" },
      scrapTo: { p_resin: 10, p_circuit: 4 }, craft: { p_resin: 16, p_circuit: 6, obj_railspike: 1 }, craftCost: 850 },
  ],

  /** 主人公の装備枠。acc1–3 は gear:"accessory" を入れる */
  gearSlots: [
    { id: "head", name: "頭部" },
    { id: "clothes", name: "服" },
    { id: "armor", name: "アーマー" },
    { id: "shoes", name: "靴" },
    { id: "mainWeapon", name: "メインウエポン" },
    { id: "subWeapon", name: "サブウエポン" },
    { id: "acc1", name: "アクセサリー１" },
    { id: "acc2", name: "アクセサリー２" },
    { id: "acc3", name: "アクセサリー３" },
  ],

  operatorBase: { hp: 100, atk: 18, anm: 12, def: 16, spd: 20, luck: 12 },
  operatorStatMax: 255,

  /**
   * 装備個体の強化。アイテムごとに Lv を積み、数値ステを底上げする。
   * 費用は暫定。予算 + 基礎部品のみ（収容品は使わない）。
   * 0→100 の合計は予算 15,650 / 金属片 550 / 合金 20 / 回路 10。
   */
  gearEnhance: {
    maxLv: 100,
    statPerLv: 0.005,
    budgetBase: 5,
    budgetPerLv: 3,
    scrapBase: 1,
    scrapEvery: 10,
    alloyEvery: 5,
    circuitEvery: 10,
  },

  /** メインウエポンのジャンル。gun はアタッチ可、blade は不可だが基礎能力が高い */
  weaponTypes: [
    { id: "gun", name: "銃" },
    { id: "blade", name: "刃" },
  ],

  /** メインウエポン専用アタッチ枠。 holster UI の種別 */
  attachSlots: [
    { id: "sight", name: "サイト" },
    { id: "barrel", name: "バレル" },
    { id: "stock", name: "ストック" },
    { id: "muzzle", name: "マズル" },
    { id: "ammo", name: "弾薬" },
    { id: "grip", name: "グリップ" },
    { id: "magazine", name: "マガジン" },
    { id: "underbarrel", name: "アンダーバレル" },
  ],

  /** 特定収容体との交戦で追加ドロップしやすい収容品 */
  objectByCatalog: {
    scp2000: "obj_seed",
    scp179: "obj_solar",
    scp2140: "obj_glyph",
    scp2932: "obj_wardlock",
    scp040jp: "obj_ofuda",
    scp173jp: "obj_toyfang",
    scp023jp: "obj_railspike",
    scp870jp: "obj_voidorb",
  },

  /**
   * クラフト可能な基本装備。収集部品から作り、主人公スロットへ装備する。
   */
  gear: [
    { id: "eq_helm", name: "戦術ヘルメット", gear: "head", rarity: "D", value: 50,
      stat: { def: 8, hp: 10 },
      skill: { name: "NVG", desc: "暗所での索敵を安定させ、防御を底上げする。" },
      scrapTo: { p_alloy: 1, p_circuit: 1 }, craft: { p_alloy: 3, p_circuit: 1 }, craftCost: 40 },
    { id: "eq_suit", name: "収容スーツ", gear: "clothes", rarity: "D", value: 45,
      stat: { hp: 12, spd: 4 },
      scrapTo: { p_resin: 3, p_tissue: 1 }, craft: { p_resin: 6, p_tissue: 2 }, craftCost: 35 },
    { id: "eq_vest", name: "プレートキャリア", gear: "armor", rarity: "C", value: 90,
      stat: { def: 18, hp: 20 },
      skill: { name: "プレート", desc: "被弾時の防御を大きく底上げする。" },
      scrapTo: { p_alloy: 3, p_scrap: 4 }, craft: { p_alloy: 6, p_scrap: 8 }, craftCost: 80 },
    { id: "eq_boots", name: "戦闘ブーツ", gear: "shoes", rarity: "D", value: 40,
      stat: { spd: 10, def: 4 },
      scrapTo: { p_resin: 2, p_scrap: 2 }, craft: { p_resin: 4, p_scrap: 4 }, craftCost: 30 },
    { id: "eq_rifle", name: "サプレスカービン", gear: "mainWeapon", weaponType: "gun", rarity: "C", value: 110,
      stat: { atk: 22 },
      skill: { name: "サプレッサー", desc: "巡回戦闘の物攻を底上げする。" },
      scrapTo: { p_alloy: 3, p_circuit: 1 }, craft: { p_alloy: 5, p_circuit: 2 }, craftCost: 90 },
    { id: "eq_pistol", name: "サイドアーム", gear: "subWeapon", rarity: "D", value: 35,
      stat: { atk: 10, luck: 3 },
      scrapTo: { p_scrap: 3, p_wire: 2 }, craft: { p_scrap: 6, p_wire: 4 }, craftCost: 25 },
    { id: "eq_nvg", name: "広域NVG", gear: "head", rarity: "B", value: 140,
      stat: { def: 14, luck: 8 },
      skill: { name: "広域NVG", desc: "暗所の索敵範囲を広げ、運を底上げする。" },
      scrapTo: { p_circuit: 3, p_alloy: 2 }, craft: { p_circuit: 5, p_alloy: 3, obj_mirror: 1 }, craftCost: 120 },
    { id: "eq_crown", name: "認可クロークヘルム", gear: "head", rarity: "A", value: 280,
      stat: { def: 20, hp: 18, luck: 6 },
      skill: { name: "Thaumiel冠", desc: "認可の重みで防御とHPを伸ばす。" },
      scrapTo: { p_cell: 2, p_anomalon: 2 }, craft: { p_cell: 4, p_anomalon: 3, obj_glyph: 1 }, craftCost: 260 },
    { id: "eq_hazmat", name: "隔離ハザードスーツ", gear: "clothes", rarity: "B", value: 130,
      stat: { hp: 22, def: 8 },
      scrapTo: { p_resin: 5, p_tissue: 2 }, craft: { p_resin: 8, p_tissue: 4, obj_ofuda: 1 }, craftCost: 110 },
    { id: "eq_cloak", name: "認知遮蔽マント", gear: "clothes", rarity: "A", value: 260,
      stat: { eva: 0.06, spd: 8, hp: 14 },
      skill: { name: "認知遮蔽", desc: "輪郭をぼかし回避を稼ぐ。" },
      scrapTo: { p_resin: 8, p_anomalon: 2 }, craft: { p_resin: 12, p_anomalon: 3, obj_ink: 1 }, craftCost: 240 },
    { id: "eq_riot", name: "鎮圧キャリア", gear: "armor", rarity: "B", value: 160,
      stat: { def: 26, hp: 24 },
      skill: { name: "鎮圧板", desc: "集団制圧時の防御を大きく底上げする。" },
      scrapTo: { p_alloy: 4, p_scrap: 6 }, craft: { p_alloy: 7, p_scrap: 10, obj_bone: 1 }, craftCost: 140 },
    { id: "eq_aegis", name: "異能防壁", gear: "armor", rarity: "A", value: 300,
      stat: { def: 34, hp: 30, anm: 8 },
      skill: { name: "イージス", desc: "異能の盾で被弾を削る。" },
      scrapTo: { p_alloy: 6, p_cell: 2 }, craft: { p_alloy: 10, p_cell: 3, obj_wardlock: 1 }, craftCost: 280 },
    { id: "eq_magboot", name: "マグブーツ", gear: "shoes", rarity: "B", value: 120,
      stat: { spd: 14, def: 8 },
      scrapTo: { p_alloy: 2, p_circuit: 2 }, craft: { p_alloy: 4, p_circuit: 3, obj_railspike: 1 }, craftCost: 100 },
    { id: "eq_phaseboot", name: "位相ブーツ", gear: "shoes", rarity: "A", value: 250,
      stat: { spd: 20, eva: 0.05 },
      skill: { name: "位相歩", desc: "半歩ずれて弾を避ける。" },
      scrapTo: { p_circuit: 3, p_anomalon: 2 }, craft: { p_circuit: 5, p_anomalon: 3, obj_key: 1 }, craftCost: 230 },
    { id: "eq_lmg", name: "分隊機関銃", gear: "mainWeapon", weaponType: "gun", rarity: "B", value: 180,
      stat: { atk: 32 },
      skill: { name: "掃射", desc: "物攻の連続射撃。" },
      scrapTo: { p_alloy: 4, p_circuit: 2 }, craft: { p_alloy: 7, p_circuit: 3, obj_blood: 1 }, craftCost: 160 },
    { id: "eq_railgun", name: "レールキャノン", gear: "mainWeapon", weaponType: "gun", rarity: "A", value: 340,
      stat: { atk: 42, crit: 0.06 },
      skill: { name: "電磁加速", desc: "物攻とクリティカルを同時に伸ばす。" },
      scrapTo: { p_alloy: 6, p_cell: 3 }, craft: { p_alloy: 10, p_cell: 4, obj_solar: 1 }, craftCost: 320 },
    { id: "eq_smg", name: "短機関銃", gear: "subWeapon", rarity: "B", value: 110,
      stat: { atk: 16, spd: 4 },
      scrapTo: { p_scrap: 5, p_wire: 3 }, craft: { p_scrap: 8, p_wire: 5, obj_toyfang: 1 }, craftCost: 90 },
    { id: "eq_disruptor", name: "異常撹乱拳銃", gear: "subWeapon", rarity: "A", value: 240,
      stat: { atk: 18, anm: 14 },
      skill: { name: "撹乱弾", desc: "物攻と異能を混ぜて撃つ。" },
      scrapTo: { p_circuit: 3, p_anomalon: 2 }, craft: { p_circuit: 5, p_anomalon: 3, obj_glyph: 1 }, craftCost: 220 },
    // 刃ジャンル。アタッチ不可の代わりに同レア帯の銃より基礎能力を高めに設定
    { id: "eq_baton", name: "特殊警棒", gear: "mainWeapon", weaponType: "blade", rarity: "D", value: 60,
      stat: { atk: 16, spd: 4 },
      skill: { name: "殴打", desc: "物攻の近接打撃。" },
      scrapTo: { p_alloy: 2, p_scrap: 2 }, craft: { p_alloy: 4, p_scrap: 4 }, craftCost: 45 },
    { id: "eq_machete", name: "鎮圧ナタ", gear: "mainWeapon", weaponType: "blade", rarity: "C", value: 150,
      stat: { atk: 30, def: 2 },
      skill: { name: "薙ぎ払い", desc: "物攻の近接攻撃。" },
      scrapTo: { p_alloy: 3, p_scrap: 3 }, craft: { p_alloy: 6, p_scrap: 6 }, craftCost: 110 },
    { id: "eq_heatblade", name: "加熱切断刀", gear: "mainWeapon", weaponType: "blade", rarity: "B", value: 240,
      stat: { atk: 44, crit: 0.05 },
      skill: { name: "灼熱斬", desc: "高熱刃で装甲ごと断つ。" },
      scrapTo: { p_alloy: 5, p_cell: 2 }, craft: { p_alloy: 8, p_cell: 3, obj_blood: 1 }, craftCost: 200 },
    { id: "eq_monoblade", name: "単分子刃", gear: "mainWeapon", weaponType: "blade", rarity: "A", value: 420,
      stat: { atk: 58, crit: 0.08, spd: 6 },
      skill: { name: "分子切断", desc: "単分子の刃であらゆる装甲を両断する。" },
      scrapTo: { p_alloy: 7, p_anomalon: 3 }, craft: { p_alloy: 12, p_anomalon: 4, obj_wardlock: 1 }, craftCost: 380 },
  ],

  /**
   * メインウエポン用アタッチメント。各種3モデル。
   * 個体ごとにレア（E〜SSパラレル）と statRange 内のロールが付く。
   * rarity はレシピ表示用の基準レア。実体の背景色はロールした個体レア。
   */
  attachments: [
    { id: "att_reddot", name: "ドットサイト", attachSlot: "sight", rarity: "D", value: 40,
      statRange: { luck: [1, 10] },
      scrapTo: { p_circuit: 1, p_scrap: 2 }, craft: { p_circuit: 2, p_scrap: 4 }, craftCost: 30 },
    { id: "att_scope", name: "4倍スコープ", attachSlot: "sight", rarity: "C", value: 90,
      statRange: { luck: [4, 12], crit: [0.01, 0.05] },
      scrapTo: { p_circuit: 2, p_alloy: 1 }, craft: { p_circuit: 4, p_alloy: 2 }, craftCost: 70 },
    { id: "att_holo", name: "ホロサイト", attachSlot: "sight", rarity: "B", value: 130,
      statRange: { luck: [2, 8], eva: [0.01, 0.04] },
      scrapTo: { p_circuit: 2, p_cell: 1 }, craft: { p_circuit: 3, p_alloy: 2, p_cell: 1 }, craftCost: 110 },
    { id: "att_carbine", name: "カービンバレル", attachSlot: "barrel", rarity: "D", value: 45,
      statRange: { atk: [1, 10] },
      scrapTo: { p_alloy: 1, p_scrap: 3 }, craft: { p_alloy: 2, p_scrap: 6 }, craftCost: 35 },
    { id: "att_long", name: "ロングバレル", attachSlot: "barrel", rarity: "C", value: 95,
      statRange: { atk: [4, 14], crit: [0.01, 0.04] },
      scrapTo: { p_alloy: 2, p_scrap: 4 }, craft: { p_alloy: 4, p_scrap: 8 }, craftCost: 75 },
    { id: "att_heavybar", name: "ヘビーバレル", attachSlot: "barrel", rarity: "B", value: 140,
      statRange: { atk: [6, 16], def: [1, 6] },
      scrapTo: { p_alloy: 3, p_scrap: 4 }, craft: { p_alloy: 5, p_scrap: 8 }, craftCost: 120 },
    { id: "att_fold", name: "折畳ストック", attachSlot: "stock", rarity: "D", value: 38,
      statRange: { def: [1, 8], spd: [1, 6] },
      scrapTo: { p_resin: 2, p_scrap: 2 }, craft: { p_resin: 4, p_scrap: 4 }, craftCost: 28 },
    { id: "att_heavy", name: "重ストック", attachSlot: "stock", rarity: "C", value: 88,
      statRange: { def: [4, 14], hp: [4, 12] },
      scrapTo: { p_alloy: 2, p_resin: 2 }, craft: { p_alloy: 4, p_resin: 4 }, craftCost: 68 },
    { id: "att_precision", name: "精密ストック", attachSlot: "stock", rarity: "B", value: 125,
      statRange: { luck: [2, 8], crit: [0.01, 0.04] },
      scrapTo: { p_alloy: 2, p_circuit: 1 }, craft: { p_alloy: 3, p_circuit: 2, p_resin: 3 }, craftCost: 100 },
    { id: "att_suppressor", name: "サプレッサー", attachSlot: "muzzle", rarity: "D", value: 42,
      statRange: { atk: [1, 8], eva: [0.01, 0.04] },
      scrapTo: { p_alloy: 1, p_wire: 2 }, craft: { p_alloy: 2, p_wire: 4 }, craftCost: 32 },
    { id: "att_brake", name: "マズルブレーキ", attachSlot: "muzzle", rarity: "C", value: 86,
      statRange: { atk: [3, 12] },
      scrapTo: { p_alloy: 2, p_scrap: 3 }, craft: { p_alloy: 4, p_scrap: 6 }, craftCost: 66 },
    { id: "att_comp", name: "コンペンセイター", attachSlot: "muzzle", rarity: "B", value: 120,
      statRange: { atk: [2, 10], luck: [1, 6] },
      scrapTo: { p_alloy: 2, p_wire: 2 }, craft: { p_alloy: 3, p_wire: 4, p_circuit: 1 }, craftCost: 95 },
    { id: "att_fmj", name: "通常弾", attachSlot: "ammo", rarity: "D", value: 24,
      statRange: { atk: [1, 10] },
      scrapTo: { p_scrap: 3 }, craft: { p_scrap: 6, p_resin: 1 }, craftCost: 18 },
    { id: "att_ap", name: "徹甲弾", attachSlot: "ammo", rarity: "C", value: 80,
      statRange: { atk: [4, 14] },
      scrapTo: { p_alloy: 1, p_scrap: 4 }, craft: { p_alloy: 2, p_scrap: 8 }, craftCost: 60 },
    { id: "att_anomaly", name: "異常弾", attachSlot: "ammo", rarity: "B", value: 150,
      statRange: { anm: [4, 14], atk: [1, 6] },
      scrapTo: { p_anomalon: 1, p_scrap: 3 }, craft: { p_anomalon: 1, p_scrap: 6, p_circuit: 1 }, craftCost: 130 },
    { id: "att_vert", name: "バーティカルグリップ", attachSlot: "grip", rarity: "D", value: 36,
      statRange: { spd: [1, 8] },
      scrapTo: { p_resin: 2, p_wire: 1 }, craft: { p_resin: 4, p_wire: 2 }, craftCost: 26 },
    { id: "att_angled", name: "アングルグリップ", attachSlot: "grip", rarity: "C", value: 78,
      statRange: { spd: [3, 10], eva: [0.01, 0.04] },
      scrapTo: { p_resin: 3, p_circuit: 1 }, craft: { p_resin: 5, p_circuit: 2 }, craftCost: 58 },
    { id: "att_ergo", name: "エルゴグリップ", attachSlot: "grip", rarity: "B", value: 115,
      statRange: { spd: [2, 8], luck: [1, 6] },
      scrapTo: { p_resin: 3, p_wire: 2 }, craft: { p_resin: 5, p_wire: 3, p_circuit: 1 }, craftCost: 88 },
    { id: "att_mag30", name: "標準マガジン", attachSlot: "magazine", rarity: "D", value: 34,
      statRange: { atk: [1, 8] },
      scrapTo: { p_scrap: 4 }, craft: { p_scrap: 8, p_alloy: 1 }, craftCost: 24 },
    { id: "att_magdrum", name: "ドラムマガジン", attachSlot: "magazine", rarity: "C", value: 92,
      statRange: { atk: [4, 14], hp: [2, 10] },
      scrapTo: { p_alloy: 2, p_scrap: 4 }, craft: { p_alloy: 3, p_scrap: 10 }, craftCost: 72 },
    { id: "att_ext", name: "拡張マガジン", attachSlot: "magazine", rarity: "B", value: 118,
      statRange: { atk: [2, 10], spd: [1, 4] },
      scrapTo: { p_alloy: 2, p_scrap: 5 }, craft: { p_alloy: 3, p_scrap: 8 }, craftCost: 90 },
    { id: "att_laser", name: "レーザーモジュール", attachSlot: "underbarrel", rarity: "D", value: 48,
      statRange: { luck: [1, 10] },
      scrapTo: { p_circuit: 1, p_wire: 2 }, craft: { p_circuit: 2, p_wire: 4 }, craftCost: 40 },
    { id: "att_gl", name: "グレネードランチャー", attachSlot: "underbarrel", rarity: "C", value: 110,
      statRange: { atk: [3, 10], anm: [3, 10] },
      scrapTo: { p_alloy: 2, p_circuit: 1 }, craft: { p_alloy: 4, p_circuit: 2, p_cell: 1 }, craftCost: 90 },
    { id: "att_bipod", name: "バイポッド", attachSlot: "underbarrel", rarity: "B", value: 128,
      statRange: { def: [2, 8], crit: [0.01, 0.04] },
      scrapTo: { p_alloy: 2, p_scrap: 3 }, craft: { p_alloy: 4, p_scrap: 6 }, craftCost: 105 },
  ],

  /**
   * 日本支部セキュリティ施設（TOKYO MAP の探索ダンジョン）。
   * 出典: http://scp-jp.wikidot.com/secure-facilities-locations-jp
   * x/y は SCP-TOKYO.jpg 上のパーセント。id を増やせばピンが増える。
   */
  defaultMapSite: "s8102",
  mapSites: [
    { id: "s8100", name: "サイト-8100", alias: "保安調査局", code: "8100", kind: "mixed", kindLabel: "司令",
      desc: "財団日本支部理事会・保安調査局。国内展開の起点。",
      x: 60, y: 23 },
    { id: "s8102", name: "サイト-8102", alias: "生物サイト-8102", code: "8102", kind: "bio", kindLabel: "生物",
      desc: "小型～中型の生物収容区域。",
      x: 26, y: 33 },
    { id: "s8104", name: "サイト-8104", alias: null, code: "8104", kind: "object", kindLabel: "非生物",
      desc: "非生物オブジェクトの収容施設。",
      x: 34, y: 48 },
    { id: "s8105", name: "サイト-8105", alias: null, code: "8105", kind: "physical", kindLabel: "物理",
      desc: "物理的な異常性を持つ、あるいは引き起こすオブジェクトの収容施設。",
      x: 78, y: 56 },
    { id: "s8114", name: "サイト-8114", alias: null, code: "8114", kind: "humanoid", kindLabel: "人型",
      desc: "高危険度人型実体などの収容施設。",
      x: 45, y: 41 },
    { id: "s8123", name: "サイト-8123", alias: null, code: "8123", kind: "object", kindLabel: "低危険",
      desc: "現在のところ大きな危険性のない物品を収容する施設。",
      x: 51, y: 58 },
    { id: "s8124", name: "サイト-8124", alias: null, code: "8124", kind: "object", kindLabel: "大型",
      desc: "大型オブジェクト収容施設。",
      x: 43, y: 71 },
    { id: "s8181", name: "サイト-8181", alias: null, code: "8181", kind: "mixed", kindLabel: "標準",
      desc: "比較的脅威の小さいSCPを収容するサイト。食堂などの設備が充実。",
      x: 39, y: 56 },
    { id: "s8182", name: "サイト-8182", alias: null, code: "8182", kind: "bio", kindLabel: "攻撃生命",
      desc: "攻撃性の強い生命型SCPを収容するサイト。複数の機動部隊が常駐。",
      x: 57, y: 82 },
    { id: "s8186", name: "サイト-8186", alias: "武装サイト-8186", code: "8186", kind: "keter", kindLabel: "武装Keter",
      desc: "山奥の極めて危険なKeterクラスを取り囲む武装サイト。強力な戦力が常駐。",
      x: 70, y: 73 },
  ],

  /** ステージ選択MAP上の再展開拠点。mapSites に入れない（探索地点ではない） */
  forwardHq: {
    id: "fwd-hq",
    name: "前線指揮所",
    code: "HQ",
    x: 57,
    y: 27,
    desc: "展開チーム全滅時のオスプレイ再展開拠点。サイト-8100 近傍。",
  },

  /** 施設 kind → 探索時の敵カタログ。未登録 kind は mixed に落ちる */
  siteEnemyPools: {
    mixed: ["scp426", "scp529", "scp860", "scp173", "scp049", "scp457", "scp650", "scp966", "scp040jp", "scp173jp"],
    bio: ["scp131", "scp529", "scp999", "scp049", "scp939", "scp682", "scp966", "scp457", "scp040jp"],
    object: ["scp173", "scp035", "scp294", "scp426", "scp113", "scp178", "scp860", "scp895", "scp914", "scp2140", "scp2000"],
    physical: ["scp087", "scp093", "scp354", "scp650", "scp457", "scp173", "scp106", "scp870jp"],
    humanoid: ["scp096", "scp049", "scp106", "scp073", "scp076", "scp085", "scp239", "scp343", "scp179"],
    keter: ["scp682", "scp106", "scp076", "scp231", "scp5000", "scp096", "scp035", "scp023jp", "scp870jp", "scp2932"],
  },

  /** Floor definitions: depth 1-50 */
  floors: (() => {
    const floors = [];
    const enemyPool = [
      "scp426", "scp529", "scp860", "scp085", "scp131", "scp040jp",
      "scp173", "scp049", "scp294", "scp457", "scp650", "scp966", "scp173jp",
      "scp096", "scp106", "scp035", "scp682", "scp076", "scp939", "scp5000",
      "scp023jp", "scp870jp", "scp179", "scp2000", "scp2932",
    ];
    const dropCatalog = [
      "scp173", "scp049", "scp131", "scp294", "scp500", "scp999", "scp529", "scp860", "scp426",
      "scp457", "scp085", "scp079", "scp087", "scp093", "scp113", "scp178", "scp650", "scp966",
      "scp939", "scp354", "scp239", "scp895", "scp055", "scp073", "scp076", "scp096", "scp106",
      "scp035", "scp682", "scp914", "scp231", "scp5000", "scp343",
      "scp040jp", "scp173jp", "scp023jp", "scp870jp", "scp179", "scp2000", "scp2140", "scp2932",
    ];
    for (let d = 1; d <= 50; d++) {
      const tier = Math.min(4, Math.floor((d - 1) / 12) + 1);
      const count = d < 5 ? 1 : d < 15 ? 2 : 3;
      const enemies = [];
      for (let i = 0; i < count; i++) {
        const pick = enemyPool[Math.min(enemyPool.length - 1, Math.floor(d / 3) + i) % enemyPool.length];
        enemies.push({ catalogId: pick, level: d + tier * 2 });
      }
      const dropChance = 0.08 + d * 0.002;
      const catalogDrop = dropCatalog[(d - 1) % dropCatalog.length];
      floors.push({
        depth: d,
        name: `区画-${String(d).padStart(2, "0")}`,
        enemies,
        xpBase: 15 + d * 8,
        budgetBase: 10 + d * 5,
        dropChance,
        catalogDrop,
        artifactChance: 0.01 + d * 0.0005,
      });
    }
    return floors;
  })(),

  /** Wiki attribution per SCP article */
  attribution: {
    wiki: {
      name: "SCP Foundation Wiki",
      url: "https://scp-wiki.wikidot.com/",
      license: "CC BY-SA 3.0",
    },
    entries: [
      { scp: "SCP-173", author: "Moto42", url: "https://scp-wiki.wikidot.com/scp-173" },
      { scp: "SCP-096", author: "Dr Dan", url: "https://scp-wiki.wikidot.com/scp-096" },
      { scp: "SCP-049", author: "djkaktus", url: "https://scp-wiki.wikidot.com/scp-049" },
      { scp: "SCP-682", author: "Dr Gears", url: "https://scp-wiki.wikidot.com/scp-682" },
      { scp: "SCP-106", author: "Dr Gears", url: "https://scp-wiki.wikidot.com/scp-106" },
      { scp: "SCP-035", author: "drb123", url: "https://scp-wiki.wikidot.com/scp-035" },
      { scp: "SCP-079", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-079" },
      { scp: "SCP-087", author: "Zaeyde", url: "https://scp-wiki.wikidot.com/scp-087" },
      { scp: "SCP-093", author: "NekoChris", url: "https://scp-wiki.wikidot.com/scp-093" },
      { scp: "SCP-131", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-131" },
      { scp: "SCP-294", author: "Arcane Researcher", url: "https://scp-wiki.wikidot.com/scp-294" },
      { scp: "SCP-500", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-500" },
      { scp: "SCP-999", author: "ProfSnider", url: "https://scp-wiki.wikidot.com/scp-999" },
      { scp: "SCP-914", author: "Arcane Researcher", url: "https://scp-wiki.wikidot.com/scp-914" },
      { scp: "SCP-055", author: "qntm", url: "https://scp-wiki.wikidot.com/scp-055" },
      { scp: "SCP-073", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-073" },
      { scp: "SCP-076", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-076" },
      { scp: "SCP-085", author: "DrClef", url: "https://scp-wiki.wikidot.com/scp-085" },
      { scp: "SCP-113", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-113" },
      { scp: "SCP-178", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-178" },
      { scp: "SCP-231", author: "DrClef", url: "https://scp-wiki.wikidot.com/scp-231" },
      { scp: "SCP-239", author: "DrClef", url: "https://scp-wiki.wikidot.com/scp-239" },
      { scp: "SCP-343", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-343" },
      { scp: "SCP-354", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-354" },
      { scp: "SCP-426", author: "Flah", url: "https://scp-wiki.wikidot.com/scp-426" },
      { scp: "SCP-457", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-457" },
      { scp: "SCP-529", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-529" },
      { scp: "SCP-650", author: "Dr Gears", url: "https://scp-wiki.wikidot.com/scp-650" },
      { scp: "SCP-860", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-860" },
      { scp: "SCP-895", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-895" },
      { scp: "SCP-939", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-939" },
      { scp: "SCP-966", author: "Unknown", url: "https://scp-wiki.wikidot.com/scp-966" },
      { scp: "SCP-5000", author: "Tanhony", url: "https://scp-wiki.wikidot.com/scp-5000" },
      { scp: "SCP-2000", author: "HammerMaiden", url: "https://scp-wiki.wikidot.com/scp-2000" },
      { scp: "SCP-179", author: "Dr Reach", url: "https://scp-wiki.wikidot.com/scp-179" },
      { scp: "SCP-2140", author: "sirpudding", url: "https://scp-wiki.wikidot.com/scp-2140" },
      { scp: "SCP-2932", author: "djkaktus", url: "https://scp-wiki.wikidot.com/scp-2932" },
      { scp: "SCP-040-JP", author: "Ikr_4185", url: "http://scp-jp.wikidot.com/scp-040-jp" },
      { scp: "SCP-173-JP", author: "SCP-JP", url: "http://scp-jp.wikidot.com/scp-173-jp" },
      { scp: "SCP-023-JP", author: "SCP-JP", url: "http://scp-jp.wikidot.com/scp-023-jp" },
      { scp: "SCP-870-JP", author: "SCP-JP", url: "http://scp-jp.wikidot.com/scp-870-jp" },
    ],
    facilitiesJp: {
      name: "セキュリティ施設-JP",
      url: "http://scp-jp.wikidot.com/secure-facilities-locations-jp",
    },
    hybridsNote: "交差種（SCP-Unknown-*）は本ゲームのオリジナル派生コンテンツ。元SCPの帰属は上記に従う。",
  },

  /** Cross-test recipes: parentA + parentB -> child catalog id */
  crossRecipes: [
    { parents: ["scp049", "scp173"], child: "x049_173" },
    { parents: ["scp914", "scp682"], child: "x914_682" },
    { parents: ["scp096", "scp076"], child: "x096_076" },
    { parents: ["scp131", "scp999"], child: "x131_999" },
    { parents: ["scp079", "scp914"], child: "x079_914" },
    { parents: ["scp035", "scp178"], child: "x035_178" },
    { parents: ["scp294", "scp500"], child: "x294_500" },
    { parents: ["scp939", "scp966"], child: "x939_966" },
    { parents: ["scp073", "scp076"], child: "x073_076" },
    { parents: ["scp106", "scp895"], child: "x106_895" },
    { parents: ["scp457", "scp354"], child: "x457_354" },
    { parents: ["scp087", "scp860"], child: "x087_860" },
    { parents: ["scp343", "scp914"], child: "x343_914" },
    { parents: ["scp055", "scp079"], child: "x055_079" },
    { parents: ["scp2000", "scp914"], child: "x2000_914" },
    { parents: ["scp040jp", "scp131"], child: "x040jp_131" },
  ],

  /** Starter catalog IDs given on new game */
  starters: ["scp131", "scp529", "scp426"],
};
